removing InsecureSkipVerify
opiproject/sztp pull request #426
Opened 2024-06-26 14:47 UTC by mohamedasifs123

closes #341

2024-06-26 16:46 UTC, glimchb commented
@mohamedasifs123 did you test it ? it fails ci for me...

2024-06-26 16:46 UTC, glimchb requested changes
@mohamedasifs123 did you test it ? it fails ci for me...

2024-06-27 12:07 UTC, bhoopesh369 commented on sztp-agent/pkg/secureagent/daemon.go
>  					//nolint:gosec
this can be removed now

2024-06-27 12:07 UTC, mohamedasifs123 commented
Yeh for me too test falling. We need to come up with another way.

2024-06-27 17:25 UTC, glimchb commented
> Yeh for me too test falling. We need to come up with another way.

so let's close this PR for now until we have a solutions

2024-06-28 01:14 UTC, closed without merging